#define HEXBUG_SPIDER_LEAD          1800, 450
#define HEXBUG_SPIDER_CONTROL_CODE  1800, 900
#define HEXBUG_SPIDER_B0            350,  550
#define HEXBUG_SPIDER_B1            350, 1450
#define HEXBUG_SPIDER_STOP          350, 0

#define HEXBUG_SPIDER_H0    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H1    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H2    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H3    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H4    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H5    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H6    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H7    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0
#define HEXBUG_SPIDER_H8    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_H9    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_HA    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_HB    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_HC    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_HD    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_HE    HEXBUG_SPIDER_B0, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1
#define HEXBUG_SPIDER_HF    HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1

#ifndef HEXBUG_SPIDER_CHANNEL
#define HEXBUG_SPIDER_CHANNEL 'A'
#endif

#if HEXBUG_SPIDER_CHANNEL == 'A'
  #define HEXBUG_SPIDER_CONTROLLER_ID      HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B1

  #define BUTTON_RIGHT      HEXBUG_SPIDER_H4, HEXBUG_SPIDER_H6
  #define BUTTON_LEFT       HEXBUG_SPIDER_H3, HEXBUG_SPIDER_H8
  #define BUTTON_FORWARD    HEXBUG_SPIDER_H1, HEXBUG_SPIDER_HC
  #define BUTTON_BACKWARD   HEXBUG_SPIDER_H2, HEXBUG_SPIDER_HA
#else
  #define HEXBUG_SPIDER_CONTROLLER_ID      HEXBUG_SPIDER_B1, HEXBUG_SPIDER_B0

  #define BUTTON_RIGHT      HEXBUG_SPIDER_H4, HEXBUG_SPIDER_H7
  #define BUTTON_LEFT       HEXBUG_SPIDER_H3, HEXBUG_SPIDER_H9
  #define BUTTON_FORWARD    HEXBUG_SPIDER_H1, HEXBUG_SPIDER_HD
  #define BUTTON_BACKWARD   HEXBUG_SPIDER_H2, HEXBUG_SPIDER_HB
#endif

#define HEXBUG_SPIDER_RIGHT      0
#define HEXBUG_SPIDER_LEFT       1
#define HEXBUG_SPIDER_FORWARD    2
#define HEXBUG_SPIDER_BACKWARD   3

#define HEXBUG_SPIDER_SIGNALS (HEXBUG_SPIDER_BACKWARD + 1)

#define HEXBUG_SPIDER_KHZ    38

#define HEXBUG_SPIDER_SIGNAL(code) { HEXBUG_SPIDER_LEAD, HEXBUG_SPIDER_CONTROL_CODE, code, HEXBUG_SPIDER_CONTROLLER_ID, HEXBUG_SPIDER_STOP }

unsigned int hexbug_spider_signal[HEXBUG_SPIDER_SIGNALS][26] = {
  HEXBUG_SPIDER_SIGNAL(BUTTON_RIGHT),
  HEXBUG_SPIDER_SIGNAL(BUTTON_LEFT),
  HEXBUG_SPIDER_SIGNAL(BUTTON_FORWARD),
  HEXBUG_SPIDER_SIGNAL(BUTTON_BACKWARD)
};
